name: Deploy Terraform Infra

on:
  push:
    branches:
      - main
    paths: ["**/*.tf"]
  pull_request:
    branches:
      - main
    paths: ["**/*.tf"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Inicializar Terraform com Backend S3
        run: |
          terraform init \
          -backend-config="bucket=${{ secrets.S3_BUCKET }}" \
          -backend-config="key=infraestrutura/state.tfstate" \
          -backend-config="region=us-east-1" \
          -backend-config="encrypt=true"
        working-directory: terraform-eks

      - name: Validar Terraform
        run: terraform validate
        working-directory: terraform-eks

      - name: Planejar Terraform
        run: terraform plan
        working-directory: terraform-eks

  deploy:
    name: Terraform Deploy
    needs: plan
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Inicializar Terraform com Backend S3
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.S3_BUCKET }}" \
            -backend-config="key=state/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="encrypt=true"
        working-directory: terraform-eks

      - name: Aplicar Terraform
        run: terraform apply -auto-approve
        working-directory: terraform-eks