name: Destroy Terraform Infra

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Confirme a destruição dos recursos'
        required: true
        default: 'yes'
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Inicializar Terraform
        run: terraform init \
          -backend-config="bucket=${{ secrets.S3_BUCKET }}" \
          -backend-config="key=infraestrutura/state.tfstate" \
          -backend-config="region=us-east-1" \
          -backend-config="encrypt=true"

      - name: Validar Terraform
        run: terraform validate

      - name: Destruir Infraestrutura
        run: |
          echo "Destruindo infraestrutura"
          terraform destroy -auto-approve
